[package]
name = "yara-x-ls"
description = """
Language Server for YARA-X.
"""
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[[bin]]
name = "yr-ls"
path = "src/main.rs"

[dependencies]
async-lsp = { version = "0.2.2", default-features=false, features=["omni-trait", "tokio", "client-monitor", "stdio"]}
bitflags = { workspace = true }
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = { version = "0.7.17", features = ["compat"] }
tower = { version = "0.5.2" , features = ["full"]}
yara-x-parser = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

